### ISSUE TITLE
无法在英语下添加新干员

### ISSUE THREAD

**Issue by 050644zf** [Houdou/arkgraph#21]
添加诸如黑等新干员时输入对应英文无法返回正确干员

**Comment by Houdou** [comment]
黑在美服还没有开放哦，这些干员都没有对应的翻译数据。为了不误导隐藏掉了~

**Comment by 050644zf** [comment]
> 黑在美服还没有开放哦，这些干员都没有对应的翻译数据。为了不误导隐藏掉了~

不他们在国服已经有官方的英文翻译，比如黑是Schwarz等等，外国也有一些国服玩家的
你可以在[这里](https://aceship.github.io/AN-EN-Tags/akhrchars.html) 看到他们的翻译

**Comment by Houdou** [comment]
那个其实是干员的 行动代号？， 英文还好啦，日服玩家就尴尬了。
美服也确实很多人提这个事，我这一两天加个开关进来好了
