### ISSUE TITLE
Recommend Most Efficient Stages to Farm

### ISSUE THREAD

**Issue by owencyr** [Houdou/arkgraph#29]
combine metadata from [Arknights Farming Guide and Important Drop Rates](https://docs.google.com/spreadsheets/u/0/d/1Fhz24nSxUef3FWplZtwPMRldyrNMc45DOcN0yaSTPaw/htmlview?pru=AAABcjUQEWo*WFydT9L2o9MMZ1aNG1Tofg#) to enhance the "Focusing Materials" display pane

**Comment by Houdou** [comment]
@owencyr 
Actually there is feature in the farming page that can do dynamic calculation to find out an efficient plan to get all materials needed.
I didn't translate that feature for global server cuz penguin stat didn't support filtering out the staging considered when generating the plan. Say, EN server player can't farm in chapter 7 right.

Good news is, they will support the level filter recently, so I can make it available to all server.
Please wait for a while, and thank you for your support!

**Comment by owencyr** [comment]
awesome news, thanks for the reply :D
