### ISSUE TITLE
能否添加目标等级功能

### ISSUE THREAD

**Issue by hiaatcnd** [Houdou/arkgraph#3]
在升级技能的时候，如果要从lv1升到lv7，需要添加6次，如果能直接计算1到7的材料，会方便很多。在此基础上，若当前等级为lv1，目标等级为lv7，升级到lv2时，也能够一键完成当前库存的修改就更好了。

**Comment by Houdou** [comment]
确实是一个问题，已经在制作另外一个页面了，大概这两天就会更新的
把同一个干员的升级需求统一放在一起编辑，然后添加到首页

**Comment by Houdou** [comment]
@hiaatcnd  做好发布啦~
