### ISSUE TITLE
Request: 關卡選擇 & 欄位排序

### ISSUE THREAD

**Issue by opaopaer** [Houdou/arkgraph#31]
首先謝謝您的建置與付出，讓我們有這麼方便的工具使用！
以下是希望追加的功能，希望您考慮考慮：

1) 添加關卡選擇功能
參考：https://www.bigfun.cn/tools/aktools/material   刷圖規則>關卡選擇

不同伺服的主線章節開放進度及當前活動不同，
導致CN服以外的伺服使用刷圖規則時無法完全參考規則
例如chap 7、以及當前CN服的活動『沃伦姆德的薄暮』，會干擾刷圖規則的演算建議

2) 培養表欄位排序功能
精確來說是『列』的移動功能。施作方法不拘，不論是浮動式拖拉、升冪降冪排序、甚至單純的上下箭頭均可

若有變更優先度的需求時，例如後來追加的技能專精、臨時追加的人物培養
雖然能透過刪除再重新追加的方式達到目的，但培養表的長度達一定程度後，該操作勢必得大量的重新拉表，
不僅使用上稍嫌不便，對流量的消耗也有一定的影響
做出優先度排序的功能也不錯

以上是我的小建議，謝謝

**Comment by Houdou** [comment]
感谢支持~
1.
现在的版本其实已经在非简体中文时过滤掉了未开放关卡，不过一直没有时间做设置开放出来。如果急用的话可以先
最近港台服开放之后也没有来得及做繁体中文的语言选项，这两天有空的话我更新一下

2.
排序功能呢。。。一直是很多用户反馈的问题之一
但是我没有找到理想的解决方案。。。（一方面也是技术力和时间不足啦。。。

我自己用的时候一般会通过调整隐藏一部分项目来做优先度的调整，比如先隐藏全部再勾选优先操作的项目
我会尽量优化排序这一块，现阶段造成的不便敬请谅解 😔 

P.S.
关于流量请不必担心，网站打开之后的操作都是在设备本地操作的，不需要联网的~
唯刷图规划需要发送少量请求到企鹅物流数据统计进行计算

**Comment by opaopaer** [comment]
@Houdou 謝謝回覆，經您的提醒才知道原來切換語言能做到過濾關卡的功能
我玩日版的關係，這資訊對我幫助很大，謝謝！

若能做出設置當然最好(因為中文名稱看習慣了)，敬候佳音，辛苦了！
