### ISSUE TITLE
干员输入安塞尔会自动识别为安比尔导致无法输入安塞尔的数据

### ISSUE THREAD

**Issue by Shiro-Choco** [Houdou/arkgraph#36]

**Comment by Houdou** [comment]
🤣  <del>她</del>他叫安赛尔 ... 不是安塞尔啦
这种错字的情况也不太好处理，安X尔到两边的文字距离相等
如果打中文字识别错误可以试试拼音(ansaier)或者代号(ansel)

之前也没有来得及做备选框，或者我看看在别的地方塞一个
