### ISSUE TITLE
库存页面无法正常显示的问题

### ISSUE THREAD

**Issue by shengyufeiling** [Houdou/arkgraph#38]
11月开始，其他页面都显示正常，但是库存页面一直不能正常显示，使用Crtl+F5强制刷新也没有用。
win10系统，遨游5和自带Edge浏览器都没办法正常加载页面，之前显示一直正常，好像就是这次更新后出现的问题
（使用的是国内镜像站https://cn.ark-nights.com/）

**Comment by Houdou** [comment]
目前看我这边试过几个浏览器都是ok的
不知道是不是有一些老版本存档数据有问题。。。

看能不能提供一下调试数据？
打开库存页面按F12，上面选项卡第二个（console或者控制台？） ，再刷新一次看一下有没有什么报错信息
![image](https://user-images.githubusercontent.com/6690811/98491588-5274cd00-2270-11eb-9969-82e315f811c9.png)

也有可能是设置文件有点问题，console下半部分输入 `copy(localStorage)` 然后粘贴到这里看看吧

**Comment by shengyufeiling** [comment]
@Houdou 
如下图
![无标题](https://user-images.githubusercontent.com/74083857/98675582-682fe280-2395-11eb-8cea-9e9d166229ce.png)

**Comment by hatoritaiga** [comment]
我的也差不多，是qq浏览器
![QQ截图20201110221737](https://user-images.githubusercontent.com/74251456/98685742-b5ff1780-23a2-11eb-8ede-399da0e98103.png)

**Comment by Houdou** [comment]
@shengyufeiling @hatoritaiga 
这个出错已经修复了，不小心使用了一些旧浏览器不支持的功能。
不过为了最佳体验，仍然推荐使用Chrome或者Edge浏览器来访问

但是发现了一些别的问题。。。我再修一下
