### ISSUE TITLE
Sorting stock by type and tier is incorrect

### ISSUE THREAD

**Issue by jwfiredragon** [Houdou/arkgraph#39]
After the addition of the new crystal materials, sorting stock by type and tier causes incorrect ordering of items, see images below. This happens in both English and Chinese, but the errors in sorting are different.
![image](https://user-images.githubusercontent.com/6947594/98758197-0e262180-2383-11eb-829c-d3546bd2dee4.png)
![image](https://user-images.githubusercontent.com/6947594/98758233-226a1e80-2383-11eb-90be-98c0a8f12aec.png)
![image](https://user-images.githubusercontent.com/6947594/98758303-504f6300-2383-11eb-8549-09ab193451c2.png)
![image](https://user-images.githubusercontent.com/6947594/98758311-547b8080-2383-11eb-9cfa-5ae1be94d673.png)

**Comment by Houdou** [comment]
Oops, sorry... I totally messed up the stock page after adding the new crystal...

Let me fix it now

**Comment by Houdou** [comment]
@jwfiredragon 
The bug should have been fixed now
Thanks for reporting the issue!
