### ISSUE TITLE
希望可以在培养表一栏中实现拖动单元格功能

### ISSUE THREAD

**Issue by kitanami** [Houdou/arkgraph#42]
rt,我是吧培养表的顺序作为精二顺序的,有时候新干员来了之后,要把他的优先度向前提那就必须要把前面很长的一部分都向后改一格,有点麻烦,或者单纯的做一个以干员的优先度作为排序也好(我现在的优先度基本上就是遵照这个顺序来的,除了部分)另外我发现了一个bug,在我点击培养表头的移除时,并不会移除当前行,而是会移除整个表的最后一行
感谢

**Comment by kitanami** [comment]
好像不一定是删除下一行,也有可能是其他行,我没有找到规律...但是在删除了数行之后似乎又正常了?挠头

**Comment by Houdou** [comment]
@kitanami 
好的，下次更新的时候我看看怎么加一下排序

**Comment by Houdou** [comment]
至于移除的bug，我这边好像没法复现，不知道有没有别的信息可以提供一下？
比如使用的浏览器，版本
最好可以看看有没有能稳定复现的步骤

**Comment by kitanami** [comment]
这个是在我新打开界面中删掉了原有的内容后开始的
Google Chrome 已是最新版本
版本 87.0.4280.141（正式版本） （64 位）
![debug](https://user-images.githubusercontent.com/68011232/104849761-d44b3b80-592e-11eb-84ca-ec6a4e13cea0.gif)

**Comment by kitanami** [comment]
在刚才我注意到还有一个另一个情况,如果表格中存在"精x等级"时候,会优先删除"精x等级"的上一个项目
![debug2](https://user-images.githubusercontent.com/68011232/104850203-09588d80-5931-11eb-967d-ea2a30d544c5.gif)

**Comment by kitanami** [comment]
目前注意到的就是这些了,辛苦了

**Comment by Houdou** [comment]
排序写好啦！
虽然不是拖动实现的（

**Comment by kitanami** [comment]
> 排序写好啦！ 虽然不是拖动实现的（

感谢
虽然已经弃坑快半年了()
