### ISSUE TITLE
关于新干员帕拉斯

### ISSUE THREAD

**Issue by deathwingssins** [Houdou/arkgraph#47]
请问大大，帕拉斯的相关信息大概什么时候更新进来

**Comment by Houdou** [comment]
不好意思这次更新完忘记推到 master 了 🙈 
前两天应该补上了

**Comment by deathwingssins** [comment]
> 不好意思这次更新完忘记推到 master 了 🙈
> 前两天应该补上了

莫事，辛苦大大啦
