### ISSUE TITLE
关于新出的两个紫色材料

### ISSUE THREAD

**Issue by deathwingssins** [Houdou/arkgraph#49]
没有像其它紫色材料一样会提醒合成公式的样子，能否修正一下？（比如我需要5个精炼溶剂，但不会提醒我需要多少个化合切削液）

**Comment by Houdou** [comment]
额……不好意思（
这种既能掉落又能合成的材料之前设计成需要手动选择是否折算合成材料了。我之后改一下这个默认行为
先可以去培养表页面加到追踪材料然后手动开一下 【折算合成材料】
![image](https://user-images.githubusercontent.com/6690811/134109812-b345a211-ae9e-48ad-92a4-d8c2466a9e77.png)

**Comment by Houdou** [comment]
已经补上了自动patch数据
