### ISSUE TITLE
在支持手动输入材料数量后发现的一个小问题

### ISSUE THREAD

**Issue by shengyufeiling** [Houdou/arkgraph#57]
首先感谢大佬，在支持手动输入后当材料数量超过1000再也不用去培养表页面单独输入了~~

然后发现了一个小问题：在更新前的刷图页面，材料数量是直接显示缺少多少个，而现在数量显示的是总共需求多少个，不会减去库存已有的数量，这样不能直观的看到还缺少多少材料，感觉看着不是很方便，不知是否BUG。

感谢~

**Comment by Houdou** [comment]
是个 bug 🙈  ………… 已经在 2.12.2 修了
把数量挪下去了，没发现这个缺少数量是图标组件里算的
