### ISSUE TITLE
建议增加表格排序或隐藏功能

### ISSUE THREAD

**Issue by deepsea666** [Houdou/arkgraph#62]
希望能增加个表格排序功能，手动拖或者增加个上下箭头都可以
培养表格长了之后要安排插队的干员就很麻烦
我也看到有其他用户提出了类似的建议，如果改变表格排序比较困难的话可以加个隐藏“隐藏项目”的功能
现在点了隐藏的项目仅仅是不在合计把所需材料里计入，那一行还是显示在培养表里的
我想能不能添加个类似“固定表头”“显示最终材料”的按钮，可以控制是否在培养表里显示或隐藏那些“隐藏项目”

**Comment by Houdou** [comment]
排序写好啦！
