### ISSUE TITLE
库存按 `种类` 分类时没有 `盐` 类材料

### ISSUE THREAD

**Issue by ABA2396** [Houdou/arkgraph#66]
![image](https://user-images.githubusercontent.com/99072975/179975485-1ae52d2f-a644-40af-8b58-614c3dda3aa7.png)

**Comment by Houdou** [comment]
我刚更新完准备 close ticket 呢（（

**Comment by ABA2396** [comment]
刚想着来看一眼怎么样了结果刚好看到更新了_(:з」∠)_

**Comment by ABA2396** [comment]
新材料 `转质盐聚块` 和 `转质盐组` 也得加加了）

**Comment by Houdou** [comment]
按说这个是11章更新的新材料（（
加好了
