### ISSUE TITLE
没有九/十章关卡掉落数据

### ISSUE THREAD

**Issue by ABA2396** [Houdou/arkgraph#68]
![image](https://user-images.githubusercontent.com/99072975/185200173-a71bdabc-ad2c-4c35-8159-0670672132a4.png)
![image](https://user-images.githubusercontent.com/99072975/185201217-62abaef4-5e2b-4611-b1b2-19bba6a99d94.png)

对应的图应该是 `main_xx-yy` 而不是 `easy_xx-yy`

**Comment by Houdou** [comment]
。。看起来是难度 mapping 漏了
等周末我修一下吧

**Comment by Houdou** [comment]
![image](https://user-images.githubusercontent.com/6690811/186413513-8c62174d-b5c7-4c0e-a7c3-7f920d496412.png)
已修复
