### ISSUE TITLE
貌似培养表中烧结核凝晶的材料计算有问题

### ISSUE THREAD

**Issue by MeisterZH** [Houdou/arkgraph#76]
rt, 并未计算是否有合成产物， 比如缺两个， 并不会算入缺少的两份的合成材料

**Comment by Houdou** [comment]
看一下是不是新材料的 折算合成材料 没打开，在培养表下面追踪材料的卡片里

**Comment by MeisterZH** [comment]
> 看一下是不是新材料的 折算合成材料 没打开，在培养表下面追踪材料的卡片里

解决了 新材料的default不折算是的是么

**Comment by Houdou** [comment]
加新材料那会忘记处理这个开关的默认数据了（扶额
