### ISSUE TITLE
培养表中材料所需理智无显示

### ISSUE THREAD

**Issue by ABA2396** [Houdou/arkgraph#79]
![image](https://github.com/Houdou/arkgraph/assets/99072975/f85f0c66-6ff9-4bec-ad14-84f6dde2e126)

**Comment by Houdou** [comment]
![image](https://github.com/Houdou/arkgraph/assets/6690811/3fe20ab8-45ae-4958-a074-6f2a44157637)
确实是换了 FBS 格式之后没兼容（
