### ISSUE TITLE
在Ark-nights.com准备的Arkplanner的导出数据不能将其导入到Arkplanner中。

### ISSUE THREAD

**Issue by tarookun** [Houdou/arkgraph#87]
我使用翻译软件。

在Ark-nights.com准备的Arkplanner的导出数据不能将其导入到Arkplanner中。

原因

在Ark-nights.com
[{"id":30135,"name":"D32钢","need":18,"have":20}]

在Arkplanner
[{"id":"30135","have":1,"need":2}]

ID号似乎需要双重引用。

[{"id":"30135","name":"D32钢","need":18,"have":20}]

您可以通过将双重报价连接到ID号来导入它。
你能修好它吗？

**Comment by Houdou** [comment]
@tarookun 
Thank you for reporting the issue!
I forgot to test the function when fixing the import issue last time. 😢
Sorry for the inconvenience.

ギットハブIDから見ると、日本の方ですね？
私、少しだけ日本語読めますので、日本語で問題を提出しでも大丈夫です！

こちらの問題では、すでに2.21.5バージョンで解決したので、どうぞもう一度試してくだだい。

**Comment by tarookun** [comment]
インポートできました。対応ありがとうございます。
