### ISSUE TITLE
佩佩的数据好像有问题

### ISSUE THREAD

**Issue by uzhao** [Houdou/arkgraph#88]
从changelog点进去的状态
![屏幕截图 2024-08-19 212034](https://github.com/user-attachments/assets/bee3e253-bf83-4a3a-a52e-273fdb1499d1)

**Comment by Houdou** [comment]
完了，好像命中生息 npc 佩佩了……

**Comment by Houdou** [comment]
已经修复了～
跳转过去的时候，从 URL 解析有多语言支持。这里忘记过滤一些不需要的角色

不过在这个页面直接搜索是没问题的
