### ISSUE TITLE
MAA的link start不亮，点击无反应

### ISSUE THREAD

**Issue by regdiliKUN** [Houdou/arkgraph#89]
问题界面如截图：
![屏幕截图 2024-10-27 145633](https://github.com/user-attachments/assets/cedc299a-ed96-4430-9ee2-f3bcefe75367)
问题是今天上午出现的，我卸载重下，反复打开maa，重启电脑都试了，仍然无法解决。

**Comment by Houdou** [comment]
MAA 的 ticket 可以提到这边：https://github.com/MaaAssistantArknights/MaaAssistantArknights
